[platformio]
src_dir = wro_car
default_envs = wro_car

[env:wro_car]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_deps = arduino-libraries/Servo

[env:huskylens]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_deps = https://github.com/HuskyLens/HUSKYLENSArduino.git
